### ISSUE TITLE
Cluster keeps resetting

### ISSUE THREAD

**Issue by Pas911** [Marcin648/e90-dashboard-ets2#7]
Hi,

first of all, thank you for all the work you put into this project. 
I tried your code but sadly I've a problem with my cluster running on it. The cluster picks up the data from the game, but the needles are jumping and the warning lights are going on and off. It just keeps resetting itself in an never ending loop.

I've already cut the termination resistor on my can shield but the problem still exists.

I'm using an Arduino Mega 2560 and the original Can Shield 2.0 from Seeed. I've even tried using an Arduino Uno and a second Can Shield but it's showing the same symptoms. For the power, I'm using a 12V 5A power supply.

I've also got 2 clusters here (9187341 and 9166828) and same happens with both off them.

And idea on what could be wrong with it?

I've attached an video file with the problem on the cluster.

https://github.com/Marcin648/e90-dashboard-ets2/assets/136792890/84662ca1-96b0-49ab-bf74-54b61f4daf32

**Comment by Marcin648** [comment]
Hi!
I had a similar issue first time. For me, cutting P1 on board really solve this issue. In general, CAN bus transmission line need two terminate 120Ohm resistor, you can add it. Value should be 120Ohm, but other close values should work as well. But.. in my case, if I add these resistors, my cluster stop working at all. My cluster working without any resistor. Also, you can try to connect grounds, Arduino GND to negative power terminal of cluster. 
5A power supply is more than needed, no issue here.
My cluster is 9166828. So it's the same that you have.

Looks like data is somehow received by cluster. Maybe you cluster have newer software version that need more can frames to work. I know that it's very important to continuing sending ignition frame, without it cluster stop working. You can experiment with this frame [here](https://github.com/Marcin648/e90-dashboard-ets2/blob/8dc87841900714f946df4c574187baffde6d3d30/src/CAN/ignition.cpp#L1) in code.
Ignition frame: http://www.loopybunny.co.uk/CarPC/can/130.html

![IMG_20230619_204251642~2](https://github.com/Marcin648/e90-dashboard-ets2/assets/16452580/aa330307-da29-4777-8b6c-8611090b8119)

Let me know if you get any results :)

**Comment by Pas911** [comment]
Grounding the cluster to both the power supply and the Arduino fixed the problem for me. Thank you so much! 🙂
